stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/COVID_IEEE

  data_preprocessing:
    cmd: python src/cnnClassifier/pipeline/stage_02_data_preprocessing.py
    deps:
      - src/cnnClassifier/pipeline/stage_02_data_preprocessing.py
      - artifacts/data_ingestion/COVID_IEEE
      - config/config.yaml
    outs:
      - artifacts/data_preprocessing/split_dataset


  
  training:
    cmd: python src/cnnClassifier/pipeline/stage_03_training.py
    deps:
      - src/cnnClassifier/pipeline/stage_03_training.py
      - config/config.yaml
      - artifacts/data_preprocessing/split_dataset
      
    params:
      - EPOCHS
      - BATCH_SIZE
      - IMG_SZ
      - LEARNING_RATE
      - WEIGHTS
    outs:
      - artifacts/training/vgg16_model.h5
